// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY04RcmIkemJr6Uj-Tokaau_FBYezYyLk',
    appId: '1:577363375409:web:44a4c1026702036b3f2c10',
    messagingSenderId: '577363375409',
    projectId: 'digital-hostel-app',
    authDomain: 'digital-hostel-app.firebaseapp.com',
    storageBucket: 'digital-hostel-app.firebasestorage.app',
    measurementId: 'G-96WKJF95JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIhJJQvnx2Biuyg72EabT3m-kMyfWvJr0',
    appId: '1:577363375409:android:c1b017d4638af7293f2c10',
    messagingSenderId: '577363375409',
    projectId: 'digital-hostel-app',
    storageBucket: 'digital-hostel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8BW-HXRp_R4YQhhChtKrGwrquiirK1pw',
    appId: '1:577363375409:ios:2c49b026dfa2a6c33f2c10',
    messagingSenderId: '577363375409',
    projectId: 'digital-hostel-app',
    storageBucket: 'digital-hostel-app.firebasestorage.app',
    androidClientId: '577363375409-e34u5veq8pavshnrqpt0v4tspvon4oiu.apps.googleusercontent.com',
    iosClientId: '577363375409-gq8u0hci8s6l5h24ptppqpsh03lmvrgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8BW-HXRp_R4YQhhChtKrGwrquiirK1pw',
    appId: '1:577363375409:ios:2c49b026dfa2a6c33f2c10',
    messagingSenderId: '577363375409',
    projectId: 'digital-hostel-app',
    storageBucket: 'digital-hostel-app.firebasestorage.app',
    androidClientId: '577363375409-e34u5veq8pavshnrqpt0v4tspvon4oiu.apps.googleusercontent.com',
    iosClientId: '577363375409-gq8u0hci8s6l5h24ptppqpsh03lmvrgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY04RcmIkemJr6Uj-Tokaau_FBYezYyLk',
    appId: '1:577363375409:web:e45031fd6328d00f3f2c10',
    messagingSenderId: '577363375409',
    projectId: 'digital-hostel-app',
    authDomain: 'digital-hostel-app.firebaseapp.com',
    storageBucket: 'digital-hostel-app.firebasestorage.app',
    measurementId: 'G-MJMGSCD44Q',
  );
}
